/**
 * DO NOT EDIT THIS FILE!
 * 
 * 
 * 
 * Helper functions to help our LEDs light up in fancy patterns
 * 
 * 
 * 
 * DO NOT EDIT THIS FILE!
**/

#include <Adafruit_NeoPixel.h>
#define PIN 14
#ifdef __AVR__
  #include <avr/power.h>
#endif

Adafruit_NeoPixel strip = Adafruit_NeoPixel(60, PIN, NEO_GRB + NEO_KHZ800);

/**
 * Color Wipe
**/
void colorWipe(uint32_t c, uint8_t wait) {
  for(uint16_t i=0; i<strip.numPixels(); i++) {
    strip.setPixelColor(i, c);
    strip.show();
    delay(wait);
  }
}

/**
 * Flash a light
 */
void flashGreenLight() {
  for(int i=0; i< strip.numPixels(); i++) {
    strip.setPixelColor(i, strip.Color(0,40,0)); // Moderately bright green color.
  }
  strip.setBrightness(64);
  strip.show();
}

/**
 * Turn all pixels off
**/
void initializeLightsToOff() {
  strip.begin();
  blackout();
}

/**
 * Cycle all colours in rainbow colours
**/
void flashRainbowLights() {
  uint16_t i, j;
  uint8_t wait = 10;
  for(j=0; j<256*5; j++) { // 5 cycles of all colors on wheel
    for(i=0; i< strip.numPixels(); i++) {
      strip.setPixelColor(i, Wheel(((i * 256 / strip.numPixels()) + j) & 255));
    }
    strip.show();
    delay(wait);
  }
  blackout();
}

/**
 * Turn all lights off
**/
void blackout() {
  strip.setPixelColor(0, 0, 0, 0);
  strip.setPixelColor(1, 0, 0, 0);
  strip.setBrightness(255);
  strip.show();
}

/**
 * move colors in a wheel pattern
**/
uint32_t Wheel(byte WheelPos) {
  WheelPos = 255 - WheelPos;
  if(WheelPos < 85) {
    return strip.Color(255 - WheelPos * 3, 0, WheelPos * 3);
  }
  if(WheelPos < 170) {
    WheelPos -= 85;
    return strip.Color(0, WheelPos * 3, 255 - WheelPos * 3);
  }
  WheelPos -= 170;
  return strip.Color(WheelPos * 3, 255 - WheelPos * 3, 0);
}
