/**
 * DO NOT EDIT THIS FILE!
 * 
 * 
 * 
 * Helper functions to fetch and compare hashtag mentions
 * 
 * 
 * 
 * DO NOT EDIT THIS FILE!
**/

int getHashtagMentionsFromServer();
boolean numberOfMentionsHasIncreased(int numberOfMentions);
boolean connectToWiFi(const char* ssid, const char* password);
