/**
 * DO NOT EDIT THIS FILE!
 * 
 * 
 * 
 * Helper functions to help our LEDs light up in fancy patterns
 * 
 * 
 * 
 * 
 * DO NOT EDIT THIS FILE!
**/

void flashGreenLight();
void colorWipe(uint32_t c, uint8_t wait);
void flashRainbowLights();
void blackout();
void initializeLightsToOff();
