/**
 * DO NOT EDIT THIS FILE!
 * 
 * 
 * 
 * Helper functions to help store values in memory
 * 
 * 
 * 
 * 
 * DO NOT EDIT THIS FILE!
**/

int getStoredNumberOfMentions();
void setStoredNumberOfMentions(int mentions);
